import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import test from "node:test";
import {
  createFeatureReviewRuntime,
  createFeatureTaskRuntime,
  runFeatureCheckCommand,
  type FeatureCheckRunner,
  type FeatureTaskSnapshot,
} from "./feature-task-runtime.ts";
import { createFeatureTaskWorktreeLifecycle } from "./feature-task-worktrees.ts";
import type { FeatureTaskGitTarget } from "./feature-task-worktrees.ts";
import {
  canonicalPlan,
  executionGraph,
  executionTask,
} from "./feature-planning.test.ts";

function git(cwd: string, args: ReadonlyArray<string>) {
  return execFileSync("git", [...args], {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();
}

function fixture(runId: string) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "pipi-task-runtime-"));
  const primary = path.join(root, "primary");
  const workingDir = path.join(root, "caller");
  const worktreeRoot = path.join(root, "task-worktrees");
  fs.mkdirSync(primary);
  fs.mkdirSync(worktreeRoot);
  git(primary, ["init", "-q"]);
  git(primary, ["config", "user.email", "test@example.com"]);
  git(primary, ["config", "user.name", "Test"]);
  fs.writeFileSync(path.join(primary, "selected.txt"), "base\n");
  fs.writeFileSync(path.join(primary, "generated.txt"), "base\n");
  git(primary, ["add", "."]);
  git(primary, ["commit", "-qm", "baseline"]);
  git(primary, [
    "worktree",
    "add",
    "-qb",
    `feature/${runId}`,
    workingDir,
    "HEAD",
  ]);
  const lifecycle = createFeatureTaskWorktreeLifecycle({
    runId,
    workingDir,
    worktreeRoot,
  });
  return {
    root,
    workingDir,
    lifecycle,
    target: lifecycle.target("root"),
    base: lifecycle.root.head,
    cleanup() {
      fs.rmSync(root, { recursive: true, force: true });
    },
  };
}

function preparedTaskFixture(runId: string) {
  const repo = fixture(runId);
  const child = repo.lifecycle.createChild("root", 1, "preparation-output");
  repo.lifecycle.notePreparationAttempt(child.id);
  fs.writeFileSync(
    path.join(child.worktree, "generated.txt"),
    "generated by preparation\n",
  );
  const preparation = repo.lifecycle.recordPreparationBaseline(child.id);
  return {
    ...repo,
    workingDir: child.worktree,
    target: repo.lifecycle.target(child.id),
    base: child.head,
    preparation,
  };
}

function recordingTarget(
  target: FeatureTaskGitTarget,
  events: string[],
): FeatureTaskGitTarget {
  return {
    ...target,
    prepareFinalization(commitPaths, discardPaths) {
      events.push("prepare");
      target.prepareFinalization?.(commitPaths, discardPaths);
    },
    commit(baseCommit, commitPaths, message) {
      events.push("commit");
      return target.commit(baseCommit, commitPaths, message);
    },
    amend(provisionalCommit, commitPaths) {
      events.push("amend");
      return target.amend(provisionalCommit, commitPaths);
    },
    continueCherryPick(commitPaths) {
      events.push("continue-cherry-pick");
      return target.continueCherryPick(commitPaths);
    },
  };
}

function requiredCheck(id = "required-check") {
  return {
    id,
    command: `run ${id}`,
    cwd: ".",
    purpose: `Verify ${id}.`,
    required: true,
  };
}

function runtimeFor(
  repo: ReturnType<typeof fixture>,
  runCheck: FeatureCheckRunner,
  signal = new AbortController().signal,
  onSnapshot?: (snapshot: FeatureTaskSnapshot) => void,
  target = repo.target,
  preparationCommands?: ReadonlyArray<string>,
) {
  const task = executionTask("implement-feature");
  return createFeatureTaskRuntime({
    kind: "task",
    task,
    canonicalPlan: canonicalPlan(),
    graph: executionGraph(),
    target,
    taskBaseCommit: repo.base,
    checks: [requiredCheck()],
    runCheck,
    signal,
    onSnapshot,
    preparationCommands,
  });
}

test("preparation replacements retain immutable inherited targets and ordered evidence", async () => {
  const repo = fixture("preparation-replacements-abcdef12");
  const inherited = ["original"];
  const calls: string[] = [];
  try {
    const runtime = runtimeFor(
      repo,
      async ({ command }) => {
        calls.push(command);
        return {
          exitCode: command === "broken" ? 1 : 0,
          stdout: "",
          stderr: "",
        };
      },
      undefined,
      undefined,
      repo.target,
      inherited,
    );
    const capsule = runtime.beginAttempt(1);
    assert.deepEqual(capsule.graphContext.preparationCommands, ["original"]);
    inherited.push("later");
    for (const command of ["fixed", "broken", "corrected"]) {
      const result = await runtime.host.prepare!({
        command,
        cwd: ".",
        purpose: "repair",
        replacesCommand: "original",
      });
      assert.equal(result.replacesCommand, "original");
      assert.equal(result.status, command === "broken" ? "failed" : "passed");
    }
    assert.deepEqual(calls, ["fixed", "broken", "corrected"]);
    assert.deepEqual(
      runtime
        .snapshot()
        .preparations?.map(({ command, status, replacesCommand }) => ({
          command,
          status,
          replacesCommand,
        })),
      [
        { command: "fixed", status: "passed", replacesCommand: "original" },
        { command: "broken", status: "failed", replacesCommand: "original" },
        { command: "corrected", status: "passed", replacesCommand: "original" },
      ],
    );
    assert.deepEqual(inherited, ["original", "later"]);
    assert.deepEqual(capsule.graphContext.preparationCommands, ["original"]);
  } finally {
    repo.cleanup();
  }
});

test("invalid preparation proposals reject atomically before running", async () => {
  const repo = fixture("preparation-invalid-abcdef12");
  try {
    let calls = 0;
    const runtime = runtimeFor(
      repo,
      async () => {
        calls++;
        return { exitCode: 0, stdout: "", stderr: "" };
      },
      undefined,
      undefined,
      repo.target,
      ["original", "duplicate", "duplicate"],
    );
    const before = runtime.snapshot();
    const valid = {
      command: "fixed",
      cwd: ".",
      purpose: "repair",
      replacesCommand: "original",
    };
    for (const override of [
      { replacesCommand: "unknown" },
      { replacesCommand: "duplicate" },
      { replacesCommand: "" },
      { replacesCommand: " original" },
      { replacesCommand: null },
      { replacesCommand: 1 },
      { command: " " },
      { command: "x".repeat(32769) },
      { command: null },
      { cwd: "./" },
      { cwd: "subdir" },
      { cwd: null },
      { purpose: null },
    ]) {
      // JSON models untyped tool input without weakening the runtime contract types.
      await assert.rejects(
        runtime.host.prepare!(
          JSON.parse(JSON.stringify({ ...valid, ...override })),
        ),
      );
      assert.deepEqual(runtime.snapshot(), before);
    }
    assert.equal(calls, 0);
  } finally {
    repo.cleanup();
  }
});

test("revoked in-flight preparation cannot leave successful replacement evidence", async () => {
  const repo = fixture("preparation-revoked-abcdef12");
  let finish!: () => void;
  const gate = new Promise<void>((resolve) => {
    finish = resolve;
  });
  try {
    const runtime = runtimeFor(
      repo,
      async () => {
        await gate;
        return { exitCode: 0, stdout: "", stderr: "" };
      },
      undefined,
      undefined,
      repo.target,
      ["original"],
    );
    const lease = runtime.host.acquireSessionLease!("repair");
    const pending = assert.rejects(
      lease.host.prepare!({
        command: "fixed",
        cwd: ".",
        purpose: "repair",
        replacesCommand: "original",
      }),
    );
    lease.revoke();
    finish();
    await pending;
    await lease.drain();
    assert.equal(runtime.snapshot().preparations?.[0]?.status, "failed");
    assert.equal(
      runtime.snapshot().preparations?.[0]?.replacesCommand,
      "original",
    );
  } finally {
    finish();
    repo.cleanup();
  }
});

test("terminal task outcomes revoke ordinary-tool authority and reject readmission", async () => {
  for (const outcome of ["accepted", "failed", "cancelled"] as const) {
    const repo = fixture(`terminal-lease-${outcome}-abcdef12`);
    try {
      const runtime = runtimeFor(repo, async () => ({
        exitCode: 0,
        stdout: "",
        stderr: "",
      }));
      runtime.beginAttempt(1);
      const lease = runtime.host.acquireSessionLease!("session");
      if (outcome === "accepted") {
        await lease.host.check({ checkId: "required-check" });
        const accepted = await lease.host.finalize({
          summary: "Verified without changes",
        });
        assert.equal(accepted.validated, true);
        runtime.settleAttempt({ status: "settled", sessionId: "session" });
      } else if (outcome === "failed") runtime.fail("Terminal failure");
      else runtime.cancel();
      assert.equal(lease.signal.aborted, true);
      await assert.rejects(lease.host.diff());
      assert.throws(() => runtime.host.acquireSessionLease!("replacement"));
      await lease.drain();
    } finally {
      repo.cleanup();
    }
  }
});

test("session leases fence every method and retain checkpoint state", async () => {
  const repo = fixture("lease-methods-abcdef12");
  try {
    const runtime = runtimeFor(repo, async () => ({
      exitCode: 0,
      stdout: "",
      stderr: "",
    }));
    const lease = runtime.host.acquireSessionLease!("first");
    assert.equal(runtime.host.acquireSessionLease!("first"), lease);
    assert.equal(lease.host.acquireSessionLease, undefined);
    assert.equal(lease.host.authoritySignal, lease.signal);
    assert.throws(() => runtime.host.acquireSessionLease!("second"));
    fs.writeFileSync(
      path.join(repo.workingDir, "selected.txt"),
      "checkpoint\n",
    );
    await lease.host.stage!({ action: "stage", paths: ["selected.txt"] });
    const checkpoint = await lease.host.checkpoint!({ message: "checkpoint" });
    lease.revoke();
    lease.revoke();
    assert.throws(() => lease.host.describe!());
    await assert.rejects(lease.host.diff());
    await assert.rejects(lease.host.check({ checkId: "required-check" }));
    await assert.rejects(
      lease.host.prepare!({ command: "true", cwd: ".", purpose: "test" }),
    );
    await assert.rejects(lease.host.stage!({ action: "stage", paths: [] }));
    await assert.rejects(lease.host.checkpoint!({ message: "old" }));
    await assert.rejects(lease.host.finalize({ summary: "old" }));
    await lease.drain();
    assert.throws(() => runtime.host.acquireSessionLease!("first"));
    const next = runtime.host.acquireSessionLease!("second");
    assert.equal((await next.host.diff()).currentHead, checkpoint.commit);
    assert.equal(runtime.snapshot().checkpointHead, checkpoint.commit);
    await runtime.host.diff();
  } finally {
    repo.cleanup();
  }
});

test(
  "session drain timeout permanently blocks replacement even after late settlement",
  { timeout: 15_000 },
  async () => {
    const repo = fixture("lease-timeout-abcdef12");
    try {
      let finish!: () => void;
      const runtime = runtimeFor(repo, async () => {
        await new Promise<void>((resolve) => {
          finish = resolve;
        });
        return { exitCode: 0, stdout: "", stderr: "" };
      });
      const lease = runtime.host.acquireSessionLease!("first");
      const rejected = assert.rejects(
        lease.host.check({ checkId: "required-check" }),
      );
      lease.revoke();
      await assert.rejects(lease.drain());
      finish();
      await rejected;
      await assert.rejects(lease.drain());
      assert.throws(() => runtime.host.acquireSessionLease!("second"));
    } finally {
      repo.cleanup();
    }
  },
);

test("review admits leases only after begin", async () => {
  const repo = fixture("lease-review-abcdef12");
  try {
    const review = createFeatureReviewRuntime({
      runId: "lease-review-abcdef12",
      workingDir: repo.workingDir,
      checks: [],
    });
    assert.throws(() => review.host.acquireSessionLease!("review"));
    review.begin(repo.base);
    const lease = review.host.acquireSessionLease!("review");
    assert.equal(review.host.acquireSessionLease!("review"), lease);
    await lease.host.diff();
    lease.revoke();
    await lease.drain();
    await assert.rejects(lease.host.diff());
  } finally {
    repo.cleanup();
  }
});

for (const operation of ["check", "prepare", "finalize"] as const) {
  test(`revoked delayed ${operation} cannot publish authoritative results`, async () => {
    const repo = fixture(`lease-delayed-${operation}-abcdef12`);
    try {
      let finish!: () => void;
      let runnerSignal: AbortSignal | undefined;
      const runtime = runtimeFor(repo, async (input) => {
        runnerSignal = input.signal;
        await new Promise<void>((resolve) => {
          finish = resolve;
        });
        return { exitCode: 0, stdout: "late", stderr: "" };
      });
      const lease = runtime.host.acquireSessionLease!("first");
      const result =
        operation === "check"
          ? lease.host.check({ checkId: "required-check" })
          : operation === "prepare"
            ? lease.host.prepare!({
                command: "true",
                cwd: ".",
                purpose: "test",
              })
            : lease.host.finalize({ summary: "test", commitPaths: [] });
      const rejected = assert.rejects(result);
      lease.revoke();
      assert.equal(runnerSignal?.aborted, true);
      let drained = false;
      const draining = lease.drain().then(() => {
        drained = true;
      });
      await Promise.resolve();
      assert.equal(drained, false);
      assert.throws(() => runtime.host.acquireSessionLease!("second"));
      finish();
      await rejected;
      await draining;
      assert.equal(runtime.isValidated(), false);
      assert.equal(runtime.snapshot().checks.length, 0);
      assert.equal(runtime.snapshot().preparations?.length, 0);
      assert.ok(runtime.host.acquireSessionLease!("second"));
    } finally {
      repo.cleanup();
    }
  });
}

test("recovery accepts exact generated output without rerunning and rejects later source edits", async () => {
  for (const mutate of [false, true]) {
    const repo = fixture(`recovery-${mutate}-abcdef12`);
    try {
      let calls = 0;
      const runtime = runtimeFor(repo, async () => {
        calls++;
        fs.writeFileSync(
          path.join(repo.workingDir, "generated.txt"),
          `version-${calls}\n`,
        );
        return { exitCode: 0, stdout: "built", stderr: "" };
      });
      runtime.beginAttempt(1);
      const checked = await runtime.host.check({ checkId: "required-check" });
      assert.equal(checked.status, "passed");
      assert.deepEqual(checked.changedPaths, ["generated.txt"]);
      assert.notEqual(
        checked.inputRevision?.fingerprint,
        checked.outputRevision?.fingerprint,
      );
      if (mutate)
        fs.writeFileSync(
          path.join(repo.workingDir, "selected.txt"),
          "later source\n",
        );
      await runtime.host.stage!({
        action: "stage",
        paths: mutate ? ["generated.txt", "selected.txt"] : ["generated.txt"],
      });
      await runtime.host.checkpoint!({ message: "checkpoint output" });
      const accepted = await runtime.host.finalize({ summary: "exact output" });
      assert.equal(accepted.validated, !mutate);
      assert.equal(calls, 1);
      assert.equal(accepted.commitRange?.headCommit, repo.target.head());
      if (mutate) assert.match(accepted.error ?? "", /Stale required check/);
    } finally {
      repo.cleanup();
    }
  }
});

test("AUD-002 revised recipes cannot remove failed original obligations", async () => {
  const repo = fixture("audit-recipes-abcdef12");
  try {
    let repaired = false;
    const runtime = runtimeFor(repo, async ({ command }) => ({
      exitCode: command === "run required-check" && !repaired ? 1 : 0,
      stdout: "",
      stderr: "",
    }));
    runtime.beginAttempt(1);
    const original = await runtime.host.check({ checkId: "required-check" });
    const revised = await runtime.host.check({
      checkId: "required-check",
      recipe: {
        command: "legitimate revised command",
        cwd: ".",
        purpose: "verify",
        reason: "recover tool",
      },
    });
    assert.equal(revised.status, "passed");
    const another = await runtime.host.check({
      checkId: "required-check",
      recipe: {
        command: "another revised command",
        cwd: ".",
        purpose: "verify again",
        reason: "additional evidence",
      },
    });
    assert.notEqual(another.checkId, revised.checkId);
    const ids = runtime.host.describe!()!.checkIds;
    assert.equal(new Set(ids).size, ids.length);
    assert.equal(
      (await runtime.host.finalize({ summary: "replacement alone" })).validated,
      false,
    );
    assert.notEqual(revised.checkId, original.checkId);
    assert.deepEqual(
      runtime
        .snapshot()
        .checks.find((check) => check.checkId === original.checkId),
      original,
    );
    repaired = true;
    const fixed = await runtime.host.check({ checkId: original.checkId });
    assert.equal(fixed.command, original.command);
    assert.equal(fixed.recipeRevision, original.recipeRevision);
    assert.equal(
      (await runtime.host.finalize({ summary: "original repaired" })).validated,
      true,
    );
    assert.deepEqual(runtime.snapshot().checkHistory?.[0], original);
  } finally {
    repo.cleanup();
  }
});

test("AUD-003 summary acceptance exempts only unchanged controller-recorded residuals", async () => {
  for (const mutation of ["none", "changed", "staged", "untracked"] as const) {
    const repo = fixture(`audit-residual-${mutation}-abcdef12`);
    try {
      fs.writeFileSync(
        path.join(repo.workingDir, "selected.txt"),
        "committed\n",
      );
      fs.writeFileSync(
        path.join(repo.workingDir, "generated.txt"),
        "retained\n",
      );
      fs.chmodSync(path.join(repo.workingDir, "generated.txt"), 0o400);
      fs.chmodSync(repo.workingDir, 0o500);
      let committed: ReturnType<typeof repo.target.commit>;
      try {
        committed = repo.target.commit(
          repo.base,
          ["selected.txt"],
          "record residual",
        );
      } finally {
        fs.chmodSync(repo.workingDir, 0o700);
        fs.chmodSync(path.join(repo.workingDir, "generated.txt"), 0o600);
      }
      const root = repo.lifecycle.branch("root");
      assert.deepEqual(root.trackedResidualPaths, ["generated.txt"]);
      const review = createFeatureReviewRuntime({
        runId: `audit-residual-${mutation}-abcdef12`,
        workingDir: repo.workingDir,
        checks: [requiredCheck()],
        runCheck: passingCheck,
        knownResidualPaths: root.trackedResidualPaths,
        knownTrackedResiduals: root.trackedResiduals,
      });
      review.begin(committed.commit);
      if (mutation === "changed")
        fs.appendFileSync(
          path.join(repo.workingDir, "generated.txt"),
          "drift\n",
        );
      if (mutation === "staged") git(repo.workingDir, ["add", "generated.txt"]);
      if (mutation === "untracked")
        fs.writeFileSync(path.join(repo.workingDir, "arbitrary.txt"), "dirt\n");
      await review.host.check({ checkId: "required-check" });
      if (mutation === "changed" || mutation === "staged") {
        await assert.rejects(
          review.host.finalize({ summary: "review" }),
          /residual changed/i,
        );
      } else {
        assert.equal(
          (await review.host.finalize({ summary: "review" })).validated,
          mutation === "none",
        );
      }
    } finally {
      fs.chmodSync(repo.workingDir, 0o700);
      repo.cleanup();
    }
  }
});

test("AUD-003 retained untracked output survives summary acceptance only unchanged", async () => {
  for (const mutation of ["none", "changed", "staged", "arbitrary"] as const) {
    const repo = fixture(`audit-untracked-${mutation}-abcdef12`);
    const output = path.join(repo.workingDir, "retained.txt");
    try {
      fs.writeFileSync(
        path.join(repo.workingDir, "selected.txt"),
        "selected\n",
      );
      fs.writeFileSync(output, "retained\n");
      fs.chmodSync(repo.workingDir, 0o500);
      let committed: ReturnType<typeof repo.target.commit>;
      try {
        committed = repo.target.commit(
          repo.base,
          ["selected.txt"],
          "retain output",
        );
      } finally {
        fs.chmodSync(repo.workingDir, 0o700);
      }
      assert.ok(committed.residualPaths.includes("retained.txt"));
      const root = repo.lifecycle.branch("root");
      assert.ok(Object.isFrozen(root.untrackedResiduals));
      assert.ok(Object.isFrozen(root.untrackedResiduals?.[0]));
      const handoff = root.untrackedResiduals!.map((record) => ({ ...record }));
      assert.deepEqual(
        handoff.map((record) => record.path),
        ["retained.txt"],
      );
      const review = createFeatureReviewRuntime({
        runId: `audit-untracked-${mutation}-abcdef12`,
        workingDir: repo.workingDir,
        checks: [requiredCheck()],
        runCheck: passingCheck,
        knownResidualPaths: committed.residualPaths,
        knownUntrackedResiduals: handoff,
      });
      handoff[0]!.fingerprint = "tampered after handoff";
      handoff.push({ path: "dirt.txt", fingerprint: "path-only claim" });
      review.begin(committed.commit);
      if (mutation === "changed") fs.appendFileSync(output, "changed\n");
      if (mutation === "staged") git(repo.workingDir, ["add", "retained.txt"]);
      if (mutation === "arbitrary")
        fs.writeFileSync(path.join(repo.workingDir, "dirt.txt"), "dirt\n");
      await review.host.check({ checkId: "required-check" });
      if (mutation === "changed" || mutation === "staged") {
        await assert.rejects(
          review.host.finalize({ summary: "review" }),
          /residual changed/i,
        );
      } else {
        assert.equal(
          (await review.host.finalize({ summary: "review" })).validated,
          mutation === "none",
        );
      }
      assert.equal(
        fs.readFileSync(output, "utf8"),
        mutation === "changed" ? "retained\nchanged\n" : "retained\n",
      );
    } finally {
      fs.chmodSync(repo.workingDir, 0o700);
      repo.cleanup();
    }
  }
});

test("summary acceptance does not inherit path-only dirt or preparation exemptions", async () => {
  const repo = fixture("audit-no-inherited-dirt-abcdef12");
  try {
    fs.writeFileSync(path.join(repo.workingDir, "arbitrary.txt"), "dirty\n");
    const runtime = createFeatureTaskRuntime({
      kind: "task",
      task: executionTask("implement-feature"),
      canonicalPlan: canonicalPlan(),
      graph: executionGraph(),
      target: repo.target,
      taskBaseCommit: repo.base,
      checks: [requiredCheck()],
      preparationBaseline: ["arbitrary.txt"],
      knownResidualPaths: ["arbitrary.txt"],
      runCheck: passingCheck,
      signal: new AbortController().signal,
    });
    runtime.beginAttempt(1);
    await runtime.host.check({ checkId: "required-check" });
    assert.equal(
      (await runtime.host.finalize({ summary: "not exempt" })).validated,
      false,
    );
  } finally {
    repo.cleanup();
  }
});

test("preparation failure is recoverable, invocation identities are global, recipes retain obligations", async () => {
  const repo = fixture("recovery-recipes-abcdef12");
  try {
    const runner: FeatureCheckRunner = async (input) => ({
      exitCode: input.kind === "prepare" ? 1 : 0,
      stdout: "",
      stderr: "diagnostic",
    });
    const first = runtimeFor(repo, runner);
    const second = runtimeFor(repo, runner);
    first.beginAttempt(1);
    second.beginAttempt(1);
    const preparation = await first.host.prepare!({
      command: "bootstrap",
      cwd: ".",
      purpose: "recover dependencies",
    });
    assert.equal(preparation.status, "failed");
    assert.equal(first.snapshot().preparations?.length, 1);
    const a = await first.host.check({ checkId: "required-check" });
    const b = await second.host.check({ checkId: "required-check" });
    assert.notEqual(a.checkInvocationId, b.checkInvocationId);
    const updated = await first.host.check({
      checkId: "required-check",
      recipe: {
        command: "replacement",
        cwd: ".",
        purpose: "verify",
        reason: "tool unavailable",
      },
      acceptanceRefs: executionTask("implement-feature").acceptanceRefs,
    });
    assert.equal(updated.required, true);
    assert.notEqual(updated.checkId, a.checkId);
    assert.equal(updated.recipeRevision, 2);
    assert.equal(first.snapshot().checkHistory?.length, 2);
    assert.equal(
      (await first.host.finalize({ summary: "verified" })).validated,
      true,
    );
    const failed = runtimeFor(repo, async () => ({
      exitCode: 2,
      stdout: "",
      stderr: "failed",
    }));
    failed.beginAttempt(1);
    assert.equal(
      (await failed.host.check({ checkId: "required-check" })).status,
      "failed",
    );
    assert.equal(
      (await failed.host.finalize({ summary: "not verified" })).validated,
      false,
    );
  } finally {
    repo.cleanup();
  }
});

test("supplementary checks preserve original failures and coverage, and reject revisions atomically", async () => {
  const repo = fixture("supplementary-abcdef12");
  try {
    const task = executionTask("implement-feature");
    const refs = task.acceptanceRefs;
    const runtime = runtimeFor(repo, async ({ command }) => ({
      exitCode: command === "run required-check" ? 1 : 0,
      stdout: "",
      stderr: "",
    }));
    runtime.beginAttempt(1);
    const original = await runtime.host.check({ checkId: "required-check" });
    const recipe = {
      command: "supplement",
      cwd: ".",
      purpose: "extra coverage",
      reason: "new verification",
    };
    for (const request of [
      { checkId: "extra", recipe },
      { checkId: "extra", recipe, acceptanceRefs: [] },
      { checkId: "extra", acceptanceRefs: refs },
      { checkId: "extra", recipe, acceptanceRefs: ["AC-UNKNOWN"] },
      { checkId: "required-check", recipe, acceptanceRefs: ["AC-UNKNOWN"] },
      {
        checkId: "required-check",
        recipe: { ...recipe, cwd: "../" },
        acceptanceRefs: refs,
      },
    ]) {
      const before = runtime.snapshot();
      const description = runtime.host.describe!();
      await assert.rejects(runtime.host.check(request));
      assert.deepEqual(runtime.snapshot(), before);
      assert.deepEqual(runtime.host.describe!(), description);
    }
    const extra = await runtime.host.check({
      checkId: "extra",
      recipe,
      acceptanceRefs: refs,
    });
    assert.equal(extra.required, true);
    assert.equal(extra.recipeRevision, 1);
    assert.deepEqual(extra.acceptanceRefs, refs);
    assert.notEqual(extra.checkInvocationId, original.checkInvocationId);
    assert.deepEqual(runtime.host.describe!()?.checkIds, [
      "required-check",
      "extra",
    ]);
    assert.deepEqual(
      runtime
        .snapshot()
        .checks.find((check) => check.checkId === original.checkId),
      original,
    );
    assert.equal(
      (
        await runtime.host.finalize({
          summary: "extra does not replace failure",
        })
      ).validated,
      false,
    );
    const revised = await runtime.host.check({
      checkId: "extra",
      acceptanceRefs: [],
    });
    assert.equal(revised.recipeRevision, 2);
    assert.deepEqual(revised.acceptanceRefs, refs);
    assert.equal(runtime.snapshot().checkHistory?.length, 3);
    assert.deepEqual(
      runtime.beginAttempt(2).checks.map((check) => check.id),
      ["required-check", "extra"],
    );
    assert.deepEqual(
      runtime.snapshot().capsule?.checks.map((check) => check.acceptanceRefs),
      [refs, refs],
    );
  } finally {
    repo.cleanup();
  }
});

test("planned explicit coverage is honored and cannot be removed by revisions", async () => {
  const repo = fixture("explicit-coverage-abcdef12");
  try {
    const task = {
      ...executionTask("implement-feature"),
      acceptanceRefs: ["AC-ONE", "AC-TWO"],
    };
    const make = (acceptanceRefs: string[]) =>
      createFeatureTaskRuntime({
        kind: "task",
        task,
        canonicalPlan: canonicalPlan(),
        graph: executionGraph(),
        target: repo.target,
        taskBaseCommit: repo.base,
        checks: [{ ...requiredCheck(), acceptanceRefs }],
        runCheck: passingCheck,
        signal: new AbortController().signal,
      });
    assert.throws(() => make(["AC-UNKNOWN"]));
    const runtime = make(["AC-ONE"]);
    runtime.beginAttempt(1);
    const first = await runtime.host.check({ checkId: "required-check" });
    assert.deepEqual(first.acceptanceRefs, ["AC-ONE"]);
    const second = await runtime.host.check({
      checkId: "required-check",
      acceptanceRefs: ["AC-TWO"],
    });
    assert.deepEqual(second.acceptanceRefs, ["AC-ONE", "AC-TWO"]);
    assert.equal(second.required, true);
    assert.equal(second.recipeRevision, 2);
    assert.deepEqual(
      runtime.snapshot().checkHistory?.map((check) => check.acceptanceRefs),
      [["AC-ONE"], ["AC-ONE", "AC-TWO"]],
    );
  } finally {
    repo.cleanup();
  }
});

const passingCheck: FeatureCheckRunner = async () => ({
  exitCode: 0,
  stdout: "passed\n",
  stderr: "",
});

function deferred<T>() {
  let resolve!: (value: T | PromiseLike<T>) => void;
  const promise = new Promise<T>((done) => {
    resolve = done;
  });
  return { promise, resolve };
}

test("runtime describes its controller workspace and declared checks", () => {
  const repo = fixture("runtime-contract-description-a1b2c3d4");
  try {
    const runtime = runtimeFor(repo, passingCheck);
    assert.deepEqual(runtime.host.describe?.(), {
      workspaceRoot: repo.workingDir,
      checkIds: ["required-check"],
    });
  } finally {
    repo.cleanup();
  }
});

test("identical in-flight checks share one runner and one history entry", async () => {
  const repo = fixture("runtime-dedup-a1b2c3d4");
  try {
    const gate = deferred<void>();
    let invocations = 0;
    const runtime = runtimeFor(repo, async () => {
      invocations += 1;
      await gate.promise;
      return { exitCode: 0, stdout: "same result\n", stderr: "" };
    });
    runtime.beginAttempt(1);

    const first = runtime.host.check({ checkId: "required-check" });
    const joined = runtime.host.check({ checkId: "required-check" });

    assert.strictEqual(joined, first);
    assert.equal(invocations, 1);
    gate.resolve();
    const [firstResult, joinedResult] = await Promise.all([first, joined]);
    assert.deepEqual(joinedResult, firstResult);
    assert.ok(firstResult.checkInvocationId);
    assert.equal(runtime.snapshot().checks.length, 1);
    assert.equal(runtime.snapshot().checkHistory?.length, 1);
    assert.equal(
      runtime.snapshot().checkHistory?.[0]?.checkInvocationId,
      firstResult.checkInvocationId,
    );
  } finally {
    repo.cleanup();
  }
});

test("dirty tracked or untracked mutation prevents an in-flight check join", async () => {
  const repo = fixture("runtime-dedup-mutation-b2c3d4e5");
  try {
    const gate = deferred<void>();
    let invocations = 0;
    const runtime = runtimeFor(repo, async () => {
      invocations += 1;
      await gate.promise;
      return { exitCode: 0, stdout: "passed\n", stderr: "" };
    });
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "dirty\n");
    fs.writeFileSync(
      path.join(repo.workingDir, "untracked.txt"),
      "untracked\n",
    );
    const first = runtime.host.check({ checkId: "required-check" });

    fs.writeFileSync(
      path.join(repo.workingDir, "selected.txt"),
      "dirty mutation\n",
    );
    await assert.rejects(
      runtime.host.check({ checkId: "required-check" }),
      /different workspace input revision/i,
    );
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "dirty\n");
    fs.writeFileSync(
      path.join(repo.workingDir, "untracked.txt"),
      "untracked mutation\n",
    );
    await assert.rejects(
      runtime.host.check({ checkId: "required-check" }),
      /different workspace input revision/i,
    );
    assert.equal(invocations, 1);

    gate.resolve();
    await first;
  } finally {
    repo.cleanup();
  }
});

test("completed checks are not cached and reruns append history", async () => {
  const repo = fixture("runtime-dedup-sequential-c3d4e5f6");
  try {
    let invocations = 0;
    const runtime = runtimeFor(repo, async () => ({
      exitCode: 0,
      stdout: `run ${++invocations}\n`,
      stderr: "",
    }));
    runtime.beginAttempt(1);

    const first = await runtime.host.check({ checkId: "required-check" });
    const second = await runtime.host.check({ checkId: "required-check" });

    assert.equal(invocations, 2);
    assert.notEqual(first.checkInvocationId, second.checkInvocationId);
    assert.notEqual(first.stdout, second.stdout);
    assert.equal(runtime.snapshot().checks.length, 1);
    assert.equal(runtime.snapshot().checkHistory?.length, 2);
    assert.deepEqual(
      runtime
        .snapshot()
        .checkHistory?.map(({ checkInvocationId }) => checkInvocationId),
      [first.checkInvocationId, second.checkInvocationId],
    );
  } finally {
    repo.cleanup();
  }
});

test("an in-flight check from another attempt cannot be reused", async () => {
  const repo = fixture("runtime-dedup-attempt-e5f6a7b8");
  try {
    const gate = deferred<void>();
    const runtime = runtimeFor(repo, async () => {
      await gate.promise;
      return { exitCode: 0, stdout: "passed\n", stderr: "" };
    });
    runtime.beginAttempt(1);
    const first = runtime.host.check({ checkId: "required-check" });
    runtime.beginAttempt(2, "retrying after an attempt transition");

    await assert.rejects(
      runtime.host.check({ checkId: "required-check" }),
      /another attempt/i,
    );
    gate.resolve();
    await assert.rejects(first, /attempt 1|current attempt/i);
  } finally {
    repo.cleanup();
  }
});

test("different checks and finalization remain serialized", async () => {
  const repo = fixture("runtime-dedup-serialize-d4e5f6a7");
  try {
    const firstCheck = requiredCheck("first-check");
    const secondCheck = requiredCheck("second-check");
    const gate = deferred<void>();
    let invocations = 0;
    const runtime = createFeatureTaskRuntime({
      kind: "task",
      task: executionTask("serialize-feature"),
      canonicalPlan: canonicalPlan(),
      graph: executionGraph(),
      target: repo.target,
      taskBaseCommit: repo.base,
      checks: [firstCheck, secondCheck],
      runCheck: async ({ command }) => {
        invocations += 1;
        if (command === firstCheck.command) await gate.promise;
        return { exitCode: 0, stdout: "passed\n", stderr: "" };
      },
      signal: new AbortController().signal,
    });
    runtime.beginAttempt(1);

    const first = runtime.host.check({ checkId: firstCheck.id });
    await assert.rejects(
      runtime.host.check({ checkId: secondCheck.id }),
      /verification is already running/i,
    );
    await assert.rejects(
      runtime.host.finalize({
        commitPaths: [],
        summary: "Finalization must wait for the active check.",
      }),
      /verification is already running/i,
    );
    assert.equal(invocations, 1);

    gate.resolve();
    await first;
    await runtime.host.check({ checkId: secondCheck.id });
    assert.equal(invocations, 2);
  } finally {
    repo.cleanup();
  }
});

test("finalization exposes its internal check only for an exact revision", async () => {
  const repo = fixture("runtime-dedup-finalize-e5f6a7b8");
  try {
    const gate = deferred<void>();
    let invocations = 0;
    const runtime = runtimeFor(repo, async () => {
      invocations += 1;
      await gate.promise;
      return { exitCode: 0, stdout: "passed\n", stderr: "" };
    });
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "feature\n");

    const finalizing = runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Finalize while the required check is in flight.",
    });
    assert.equal(invocations, 1);
    fs.writeFileSync(
      path.join(repo.workingDir, "late-untracked.txt"),
      "late mutation\n",
    );
    await assert.rejects(
      runtime.host.check({ checkId: "required-check" }),
      /different workspace input revision/i,
    );
    fs.rmSync(path.join(repo.workingDir, "late-untracked.txt"));
    const joined = runtime.host.check({ checkId: "required-check" });
    const joinedAgain = runtime.host.check({ checkId: "required-check" });
    assert.strictEqual(joinedAgain, joined);
    assert.equal(invocations, 1);

    gate.resolve();
    const [checkResult, finalized] = await Promise.all([joined, finalizing]);
    assert.equal(finalized.validated, true);
    assert.deepEqual(finalized.checks, [checkResult]);
  } finally {
    repo.cleanup();
  }
});

test("a failed check releases its operation for a later run", async () => {
  const repo = fixture("runtime-dedup-failure-f6a7b8c9");
  try {
    let invocations = 0;
    const runtime = runtimeFor(repo, async () => {
      if (++invocations === 1) throw new Error("runner failure");
      return { exitCode: 0, stdout: "recovered\n", stderr: "" };
    });
    runtime.beginAttempt(1);

    const failed = await runtime.host.check({ checkId: "required-check" });
    const recovered = await runtime.host.check({ checkId: "required-check" });

    assert.equal(failed.status, "failed");
    assert.equal(recovered.status, "passed");
    assert.equal(invocations, 2);
    assert.equal(runtime.snapshot().checkHistory?.length, 2);
  } finally {
    repo.cleanup();
  }
});

test("cancelling an in-flight check rejects it and closes its operation", async () => {
  const repo = fixture("runtime-dedup-cancel-a7b8c9d0");
  try {
    const cancellation = new AbortController();
    const gate = deferred<void>();
    const runtime = runtimeFor(
      repo,
      async ({ signal }) => {
        await gate.promise;
        return signal.aborted
          ? { exitCode: null, stdout: "", stderr: "cancelled" }
          : { exitCode: 0, stdout: "passed\n", stderr: "" };
      },
      cancellation.signal,
    );
    runtime.beginAttempt(1);
    const check = runtime.host.check({ checkId: "required-check" });
    cancellation.abort();
    gate.resolve();

    await assert.rejects(check, /cancelled/i);
    await assert.rejects(
      runtime.host.check({ checkId: "required-check" }),
      /cancelled|authority is closed/i,
    );
  } finally {
    repo.cleanup();
  }
});

test("failed required verification leaves a provisional commit that a later attempt amends", async () => {
  const repo = fixture("runtime-amend-a1b2c3d4");
  try {
    let checkAttempt = 0;
    const runtime = runtimeFor(repo, async () => ({
      exitCode: ++checkAttempt === 1 ? 1 : 0,
      stdout: "",
      stderr: checkAttempt === 1 ? "first verification failed" : "",
    }));
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "first\n");

    const first = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Implemented the first version and ran its required check.",
    });

    assert.equal(first.validated, false);
    assert.equal(first.status, "provisional");
    assert.ok(first.commit);
    const settled = runtime.settleAttempt({
      status: "settled",
      sessionId: "luna-attempt-1",
    });
    assert.equal(settled.error, first.error);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "fixed\n");
    const retry = runtime.beginAttempt(2, first.error);
    assert.equal(retry.graphContext.provisionalCommit, first.commit);

    const repaired = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Repaired the failed behavior and reran verification.",
    });

    assert.equal(repaired.validated, true);
    assert.equal(repaired.status, "validated");
    assert.notEqual(repaired.commit, first.commit);
    assert.equal(
      git(repo.workingDir, ["rev-list", "--count", `${repo.base}..HEAD`]),
      "1",
    );
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD^"]), repo.base);
    assert.equal(runtime.snapshot().validatedCommit, repaired.commit);
  } finally {
    repo.cleanup();
  }
});

test("a provisional commit can be validated unchanged with empty paths on retry", async () => {
  const repo = fixture("runtime-empty-retry-e2f3a4b5");
  try {
    let checks = 0;
    const runtime = runtimeFor(repo, async () => {
      checks += 1;
      return {
        exitCode: checks === 1 ? 1 : 0,
        stdout: checks === 1 ? "transient failure\n" : "passed\n",
        stderr: "",
      };
    });
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "first\n");

    const first = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Created the implementation before a transient check failure.",
    });

    assert.equal(first.validated, false);
    assert.equal(first.status, "provisional");
    assert.ok(first.commit);
    assert.equal(checks, 1);
    const provisional = first.commit;
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), provisional);
    assert.equal(
      git(repo.workingDir, ["rev-list", "--count", `${repo.base}..HEAD`]),
      "1",
    );

    const settled = runtime.settleAttempt({ status: "settled" });
    assert.equal(settled.status, "provisional");
    assert.equal(settled.error, first.error);
    const retry = runtime.beginAttempt(2, first.error);
    assert.equal(retry.graphContext.provisionalCommit, provisional);

    const finalized = await runtime.host.finalize({
      commitPaths: [],
      summary: "Rechecked the unchanged provisional implementation.",
    });

    assert.equal(finalized.validated, true);
    assert.equal(finalized.status, "validated");
    assert.equal(finalized.commit, provisional);
    assert.equal(checks, 2);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), provisional);
    assert.equal(
      git(repo.workingDir, ["rev-list", "--count", `${repo.base}..HEAD`]),
      "1",
    );
    assert.equal(git(repo.workingDir, ["status", "--porcelain"]), "");
    assert.equal(runtime.snapshot().validatedCommit, provisional);
    assert.equal(runtime.snapshot().status, "validated");
    assert.equal(runtime.isValidated(), true);
    await assert.rejects(
      runtime.host.finalize({
        commitPaths: [],
        summary: "Authority must remain closed after validation.",
      }),
      /authority is closed/i,
    );
  } finally {
    repo.cleanup();
  }
});

test("empty retry paths reject new tracked and untracked work after a provisional commit", async () => {
  const repo = fixture("runtime-pending-retry-f3a4b5c6");
  try {
    let checks = 0;
    const runtime = runtimeFor(repo, async () => {
      checks += 1;
      return {
        exitCode: checks === 1 ? 1 : 0,
        stdout: checks === 1 ? "transient failure\n" : "passed\n",
        stderr: "",
      };
    });
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "first\n");

    const first = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Created a provisional implementation for the retry fixture.",
    });

    assert.equal(first.validated, false);
    assert.equal(first.status, "provisional");
    assert.ok(first.commit);
    runtime.settleAttempt({ status: "settled" });
    runtime.beginAttempt(2, first.error);
    fs.writeFileSync(
      path.join(repo.workingDir, "selected.txt"),
      "new tracked work\n",
    );
    fs.writeFileSync(
      path.join(repo.workingDir, "new-output.txt"),
      "new untracked work\n",
    );

    await assert.rejects(
      runtime.host.finalize({
        commitPaths: [],
        summary: "Attempted to discard pending retry work.",
      }),
      /cannot discard meaningful task changes: new-output\.txt, selected\.txt/i,
    );

    assert.equal(checks, 1);
    assert.equal(runtime.snapshot().status, "retrying");
    assert.equal(runtime.snapshot().validatedCommit, undefined);
    assert.equal(runtime.isValidated(), false);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), first.commit);
    assert.equal(
      git(repo.workingDir, ["status", "--porcelain"]),
      "M selected.txt\n?? new-output.txt",
    );

    const finalized = await runtime.host.finalize({
      commitPaths: ["selected.txt", "new-output.txt"],
      summary: "Included the pending tracked and untracked retry work.",
    });

    assert.equal(finalized.validated, true);
    assert.equal(finalized.status, "validated");
    assert.equal(checks, 2);
    assert.equal(git(repo.workingDir, ["status", "--porcelain"]), "");
    assert.equal(
      git(repo.workingDir, ["rev-list", "--count", `${repo.base}..HEAD`]),
      "1",
    );
  } finally {
    repo.cleanup();
  }
});

test("controller whitespace checks see provisional commits without granting shell Git authority", async () => {
  const repo = fixture("runtime-git-check-a3b4c5d6");
  try {
    const signal = new AbortController().signal;
    const runtime = createFeatureTaskRuntime({
      kind: "task",
      task: executionTask("implement-feature"),
      canonicalPlan: canonicalPlan(),
      graph: executionGraph(),
      target: repo.target,
      taskBaseCommit: repo.base,
      checks: [{ ...requiredCheck("whitespace"), command: "git diff --check" }],
      signal,
    });
    runtime.beginAttempt(1);
    fs.writeFileSync(
      path.join(repo.workingDir, "selected.txt"),
      "trailing space \n",
    );
    const first = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Whitespace regression fixture.",
    });
    assert.equal(first.validated, false);
    assert.equal(first.checks[0]!.exitCode, 2);
    assert.ok(first.checks[0]!.stdout.includes("selected.txt"));
    assert.equal(git(repo.workingDir, ["status", "--porcelain"]), "");
    runtime.settleAttempt({ status: "settled" });
    runtime.beginAttempt(2, first.error);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "fixed\n");
    const repaired = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Remove trailing whitespace.",
    });
    assert.equal(repaired.validated, true);
    const head = git(repo.workingDir, ["rev-parse", "HEAD"]);
    const denied = await runFeatureCheckCommand({
      kind: "check",
      workspaceRoot: repo.workingDir,
      cwd: repo.workingDir,
      command: "git diff --check; git update-ref HEAD HEAD^",
      signal,
    });
    assert.notEqual(denied.exitCode, 0);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), head);
    await assert.rejects(
      runFeatureCheckCommand({
        kind: "check",
        workspaceRoot: repo.workingDir,
        cwd: repo.root,
        command: "git diff --check",
        signal,
      }),
      /unsafe|escapes/,
    );
    await assert.rejects(
      runFeatureCheckCommand({
        kind: "check",
        workspaceRoot: repo.workingDir,
        cwd: repo.workingDir,
        command: "git diff --check",
        signal: AbortSignal.abort(),
      }),
      /cancelled/,
    );
  } finally {
    repo.cleanup();
  }
});

test("controller whitespace checks cannot invoke Git-configured executable helpers", async () => {
  const repo = fixture("runtime-git-drivers-b4c5d6e7");
  try {
    const marker = path.join(repo.root, "helper-executed");
    const program = path.join(repo.root, "helper.sh");
    fs.writeFileSync(program, `#!/bin/sh\ntouch '${marker}'\ncat\n`, {
      mode: 0o755,
    });
    fs.writeFileSync(
      path.join(repo.workingDir, ".gitattributes"),
      "*.txt filter=probe diff=probe\n",
    );
    for (const key of [
      "filter.probe.clean",
      "filter.probe.process",
      "diff.probe.command",
      "diff.probe.textconv",
      "core.fsmonitor",
    ]) {
      git(repo.workingDir, ["config", key, program]);
    }
    git(repo.workingDir, ["config", "filter.probe.required", "true"]);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "changed \n");
    const result = await runFeatureCheckCommand({
      kind: "check",
      workspaceRoot: repo.workingDir,
      cwd: repo.workingDir,
      command: "git diff --check",
      diffBaseCommit: repo.base,
      signal: new AbortController().signal,
    });
    assert.equal(result.exitCode, 2, result.stderr);
    assert.equal(fs.existsSync(marker), false);
  } finally {
    repo.cleanup();
  }
});

test("large Git whitespace diagnostics are drained without losing the real exit code", async () => {
  const repo = fixture("runtime-large-check-c5d6e7f8");
  try {
    fs.writeFileSync(
      path.join(repo.workingDir, "selected.txt"),
      Array.from(
        { length: 15000 },
        (_, i) => `line ${i} with trailing space \n`,
      ).join(""),
    );
    const result = await runFeatureCheckCommand({
      kind: "check",
      workspaceRoot: repo.workingDir,
      cwd: repo.workingDir,
      command: "git diff --check",
      diffBaseCommit: repo.base,
      signal: new AbortController().signal,
    });
    assert.equal(result.exitCode, 2, result.stderr);
    assert.ok(result.stdout.startsWith("selected.txt:"));
    assert.ok(result.stdout.endsWith("[Output truncated.]"));
    assert.ok(Buffer.byteLength(result.stdout) <= 256 * 1024 + 32);
  } finally {
    repo.cleanup();
  }
});

test("cancellation settles a mediated Git command blocked reading a config FIFO", async () => {
  const repo = fixture("runtime-cancel-git-d6e7f8a9");
  try {
    const fifo = path.join(repo.root, "blocked-config");
    execFileSync("mkfifo", [fifo]);
    git(repo.workingDir, ["config", "include.path", fifo]);
    const started = Date.now();
    const result = await runFeatureCheckCommand({
      kind: "check",
      workspaceRoot: repo.workingDir,
      cwd: repo.workingDir,
      command: "git diff --check",
      signal: AbortSignal.timeout(100),
    });
    assert.equal(result.exitCode, null);
    assert.match(result.stderr, /cancelled/);
    assert.ok(Date.now() - started < 3000);
  } finally {
    repo.cleanup();
  }
});

test("no-change finalization runs required checks without creating an empty commit", async () => {
  const repo = fixture("runtime-no-change-b1c2d3e4");
  try {
    let checks = 0;
    const runtime = runtimeFor(repo, async () => {
      checks += 1;
      return { exitCode: 0, stdout: "passed\n", stderr: "" };
    });
    runtime.beginAttempt(1);

    const result = await runtime.host.finalize({
      commitPaths: [],
      summary: "The accepted behavior already exists and verification passed.",
    });

    assert.equal(result.validated, true);
    assert.equal(result.status, "satisfied_without_changes");
    assert.equal(result.commit, undefined);
    assert.equal(checks, 1);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), repo.base);
  } finally {
    repo.cleanup();
  }
});

test("empty commit paths cannot discard meaningful dirty work", async () => {
  const repo = fixture("runtime-dirty-empty-c1d2e3f4");
  try {
    const runtime = runtimeFor(repo, passingCheck);
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "dirty\n");

    await assert.rejects(
      runtime.host.finalize({
        commitPaths: [],
        summary: "Attempted an invalid no-change finalization.",
      }),
      /cannot discard meaningful task changes/i,
    );
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), repo.base);
    assert.equal(
      fs.readFileSync(path.join(repo.workingDir, "selected.txt"), "utf8"),
      "dirty\n",
    );
  } finally {
    repo.cleanup();
  }
});

test("an aborted task signal prevents commit creation", async () => {
  const repo = fixture("runtime-cancel-d1e2f3a4");
  try {
    const cancellation = new AbortController();
    const runtime = runtimeFor(repo, passingCheck, cancellation.signal);
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "cancelled\n");
    cancellation.abort();

    await assert.rejects(
      runtime.host.finalize({
        commitPaths: ["selected.txt"],
        summary: "Cancellation arrived before finalization.",
      }),
      /cancelled/i,
    );
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), repo.base);
  } finally {
    repo.cleanup();
  }
});

test("same-branch HEAD drift blocks empty finalization", async () => {
  const repo = fixture("runtime-head-drift-e1f2a3b4");
  try {
    const runtime = runtimeFor(repo, passingCheck);
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "external\n");
    git(repo.workingDir, ["add", "selected.txt"]);
    git(repo.workingDir, ["commit", "-qm", "external same-branch commit"]);
    const driftedHead = git(repo.workingDir, ["rev-parse", "HEAD"]);

    await assert.rejects(
      runtime.host.finalize({
        commitPaths: [],
        summary: "Must not accept a different same-branch HEAD.",
      }),
      /head.*drift|drifted.*head|controller ownership/i,
    );
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), driftedHead);
    assert.notEqual(driftedHead, repo.base);
  } finally {
    repo.cleanup();
  }
});

test("tracked files changed by a check require an explicit later amend", async () => {
  const repo = fixture("runtime-check-mutation-f1a2b3c4");
  try {
    let checkAttempt = 0;
    const runtime = runtimeFor(repo, async () => {
      checkAttempt += 1;
      if (checkAttempt === 1) {
        fs.writeFileSync(
          path.join(repo.workingDir, "generated.txt"),
          "generated by check\n",
        );
      }
      return { exitCode: 0, stdout: "passed\n", stderr: "" };
    });
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "feature\n");

    const first = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Implemented the feature before generated output appeared.",
    });

    assert.equal(first.validated, false);
    assert.equal(first.status, "provisional");
    assert.deepEqual(first.checks[0]?.changedPaths, ["generated.txt"]);
    runtime.settleAttempt({ status: "settled", error: first.error });
    runtime.beginAttempt(2, first.error);

    const amended = await runtime.host.finalize({
      commitPaths: ["generated.txt"],
      summary: "Explicitly included the verified generated source update.",
    });

    assert.equal(amended.validated, true);
    assert.equal(
      git(repo.workingDir, ["rev-list", "--count", `${repo.base}..HEAD`]),
      "1",
    );
    assert.deepEqual(
      git(repo.workingDir, ["diff", "--name-only", `${repo.base}..HEAD`])
        .split("\n")
        .sort(),
      ["generated.txt", "selected.txt"],
    );
  } finally {
    repo.cleanup();
  }
});

test("large failed-check evidence produces a bounded retry capsule with current diff", async () => {
  const repo = fixture("runtime-large-output-a2b3c4d5");
  try {
    const hugeOutput = "failure detail ".repeat(64 * 1024);
    const runtime = runtimeFor(repo, async () => ({
      exitCode: 1,
      stdout: hugeOutput,
      stderr: hugeOutput,
    }));
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "feature\n");
    const first = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary:
        "Created a provisional implementation before verification failed.",
    });
    assert.equal(first.validated, false);
    runtime.settleAttempt({ status: "settled", error: first.error });
    fs.writeFileSync(
      path.join(repo.workingDir, "generated.txt"),
      "retry work\n",
    );

    const retry = runtime.beginAttempt(2, first.error);

    assert.ok(Buffer.byteLength(JSON.stringify(retry), "utf8") <= 192 * 1024);
    assert.equal(retry.graphContext.previousFailure, first.error);
    assert.equal(retry.graphContext.provisionalCommit, first.commit);
    assert.ok(retry.graphContext.previousChecks.length > 0);
    assert.ok(
      Buffer.byteLength(retry.graphContext.previousChecks[0]!.stdout, "utf8") <
        Buffer.byteLength(hugeOutput, "utf8"),
    );
    assert.ok(retry.graphContext.currentDiff);
    assert.equal(retry.graphContext.currentDiff.truncated, false);
    assert.ok(retry.graphContext.currentDiff.text.includes("retry work"));
  } finally {
    repo.cleanup();
  }
});

test("final-review snapshots update and supplied cancellation prevents a review commit", async () => {
  const repo = fixture("runtime-review-b2c3d4e5");
  try {
    const snapshots: FeatureTaskSnapshot[] = [];
    const cancellation = new AbortController();
    const review = createFeatureReviewRuntime({
      runId: "runtime-review-b2c3d4e5",
      workingDir: repo.workingDir,
      checks: [requiredCheck("review-check")],
      runCheck: passingCheck,
      signal: cancellation.signal,
      canonicalPlan: canonicalPlan(),
      graph: executionGraph(),
      onSnapshot: (snapshot) => snapshots.push(snapshot),
    });
    assert.equal(review.snapshot().status, "waiting");
    review.begin(repo.base);
    assert.equal(review.snapshot().status, "running");
    fs.writeFileSync(
      path.join(repo.workingDir, "selected.txt"),
      "review edit\n",
    );
    cancellation.abort();

    await assert.rejects(
      review.host.finalize({
        commitPaths: ["selected.txt"],
        summary: "Review cancellation arrived before finalization.",
      }),
      /cancelled/i,
    );

    assert.equal(review.snapshot().status, "running");
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), repo.base);
    assert.ok(snapshots.some(({ status }) => status === "waiting"));
    assert.ok(snapshots.some(({ status }) => status === "running"));
  } finally {
    repo.cleanup();
  }
});

test("large task diffs page to the exact tail and finalize without an output cap", async () => {
  const repo = fixture("runtime-large-diff-c3d4e5f6");
  try {
    const runtime = runtimeFor(repo, passingCheck);
    runtime.beginAttempt(1);
    const tail = "PIPI-DIFF-TAIL-SENTINEL";
    fs.writeFileSync(
      path.join(repo.workingDir, "selected.txt"),
      `${"large normal feature content\n".repeat(100_000)}${tail}\n`,
    );
    const expected = execFileSync(
      "git",
      ["diff", "--no-ext-diff", "--binary", repo.base, "--"],
      {
        cwd: repo.workingDir,
        maxBuffer: 8 * 1024 * 1024,
        stdio: ["ignore", "pipe", "pipe"],
      },
    );
    assert.ok(expected.length > 2 * 1024 * 1024);
    const expectedFingerprint = createHash("sha256")
      .update(expected)
      .digest("hex");

    const pages: string[] = [];
    let request: { offset?: number; fingerprint?: string } | undefined;
    let firstFingerprint: string | undefined;
    while (true) {
      const result = await runtime.host.diff(request);
      pages.push(result.diff.text);
      firstFingerprint ??= result.diff.fingerprint;
      assert.equal(result.diff.bytes, expected.length);
      assert.equal(result.diff.fingerprint, expectedFingerprint);
      if (result.diff.nextOffset === undefined) break;
      request = {
        offset: result.diff.nextOffset,
        fingerprint: result.diff.fingerprint,
      };
    }
    assert.equal(pages.join(""), expected.toString("utf8"));
    assert.ok(pages.at(-1)?.includes(tail));

    fs.appendFileSync(path.join(repo.workingDir, "selected.txt"), "drift\n");
    await assert.rejects(
      runtime.host.diff({ offset: 1, fingerprint: firstFingerprint }),
      /diff changed/i,
    );
    const finalized = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Committed the normal large feature after complete inspection.",
    });
    assert.equal(finalized.validated, true);
    assert.equal(finalized.status, "validated");
  } finally {
    repo.cleanup();
  }
});

test("final review pages from the feature base while commits remain based on execution HEAD", async () => {
  const repo = fixture("runtime-review-base-d4e5f6a7");
  try {
    fs.writeFileSync(
      path.join(repo.workingDir, "selected.txt"),
      "implemented\n",
    );
    git(repo.workingDir, ["add", "selected.txt"]);
    git(repo.workingDir, ["commit", "-qm", "feature implementation"]);
    const executionHead = git(repo.workingDir, ["rev-parse", "HEAD"]);
    const review = createFeatureReviewRuntime({
      runId: "runtime-review-base-d4e5f6a7",
      workingDir: repo.workingDir,
      checks: [requiredCheck("review-check")],
      runCheck: passingCheck,
      canonicalPlan: canonicalPlan(),
      graph: executionGraph(),
      diffBaseCommit: repo.base,
    });
    review.begin(executionHead);
    assert.deepEqual(review.host.describe?.(), {
      workspaceRoot: repo.workingDir,
      checkIds: ["review-check"],
    });

    const evidence = await review.host.diff();
    assert.deepEqual(evidence.baseToHead, ["selected.txt"]);
    assert.ok(evidence.diff.text.includes("implemented"));
    fs.writeFileSync(path.join(repo.workingDir, "generated.txt"), "reviewed\n");
    const finalized = await review.host.finalize({
      commitPaths: ["generated.txt"],
      summary: "Reviewed the whole feature and added a bounded correction.",
    });

    assert.equal(finalized.validated, true);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD^"]), executionHead);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD^^"]), repo.base);
  } finally {
    repo.cleanup();
  }
});

test("final review rejects drift from the trusted root residual fingerprint", () => {
  const repo = fixture("runtime-review-residual-e5f6a7b8");
  try {
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "committed\n");
    fs.writeFileSync(path.join(repo.workingDir, "generated.txt"), "retained\n");
    fs.chmodSync(path.join(repo.workingDir, "generated.txt"), 0o400);
    fs.chmodSync(repo.workingDir, 0o500);
    let committed: ReturnType<typeof repo.target.commit>;
    try {
      committed = repo.target.commit(
        repo.base,
        ["selected.txt"],
        "record cleanup residual",
      );
    } finally {
      fs.chmodSync(repo.workingDir, 0o700);
      fs.chmodSync(path.join(repo.workingDir, "generated.txt"), 0o600);
    }
    const rootState = repo.lifecycle.branch("root");
    assert.deepEqual(rootState.trackedResidualPaths, ["generated.txt"]);
    fs.appendFileSync(
      path.join(repo.workingDir, "generated.txt"),
      "same-path drift\n",
    );
    const review = createFeatureReviewRuntime({
      runId: "runtime-review-residual-e5f6a7b8",
      workingDir: repo.workingDir,
      checks: [requiredCheck("review-check")],
      runCheck: passingCheck,
      knownResidualPaths: rootState.trackedResidualPaths,
      knownTrackedResiduals: rootState.trackedResiduals,
    });

    assert.throws(
      () => review.begin(committed.commit),
      /recorded cleanup residual changed/i,
    );
  } finally {
    fs.chmodSync(repo.workingDir, 0o700);
    repo.cleanup();
  }
});

test("preparation changes appear in the first capsule and diff evidence", async () => {
  const repo = preparedTaskFixture("runtime-preparation-capsule-a1b2c3d4");
  try {
    const runtime = runtimeFor(repo, passingCheck);
    const capsule = runtime.beginAttempt(1);
    const capsuleChanges = capsule.graphContext.preparationChanges;
    assert.deepEqual(
      capsuleChanges?.map(({ path: filePath }) => filePath),
      ["generated.txt"],
    );
    assert.ok(capsuleChanges?.[0]?.fingerprint);
    assert.ok(
      capsule.graphContext.currentDiff?.text.includes(
        "generated by preparation",
      ),
    );

    const evidence = await runtime.host.diff();
    assert.deepEqual(
      evidence.preparationChanges?.map(({ path: filePath }) => filePath),
      ["generated.txt"],
    );
    assert.equal(
      evidence.preparationChanges?.[0]?.fingerprint,
      capsuleChanges?.[0]?.fingerprint,
    );
    assert.ok(evidence.diff.text.includes("generated by preparation"));
    assert.equal(
      capsule.graphContext.currentDiff?.fingerprint,
      evidence.diff.fingerprint,
    );
    assert.ok(evidence.diff.bytes > 0);
  } finally {
    repo.cleanup();
  }
});

test("omitting a preparation path is non-destructive and an explicit commit can retry", async () => {
  const repo = preparedTaskFixture("runtime-preparation-selection-b2c3d4e5");
  try {
    let checks = 0;
    const runtime = runtimeFor(repo, async () => {
      checks += 1;
      return { exitCode: 0, stdout: "passed\n", stderr: "" };
    });
    runtime.beginAttempt(1);
    const beforeHead = git(repo.workingDir, ["rev-parse", "HEAD"]);
    const generated = path.join(repo.workingDir, "generated.txt");
    const beforeContent = fs.readFileSync(generated, "utf8");

    await assert.rejects(
      runtime.host.finalize({
        commitPaths: [],
        summary: "Leave the preparation output uncommitted for review.",
      }),
    );
    assert.equal(checks, 0);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), beforeHead);
    assert.equal(fs.readFileSync(generated, "utf8"), beforeContent);
    assert.deepEqual(
      git(repo.workingDir, ["diff", "--name-only"]).split("\n"),
      ["generated.txt"],
    );

    const finalized = await runtime.host.finalize({
      commitPaths: ["generated.txt"],
      summary: "Include the verified preparation output in the task commit.",
    });
    assert.equal(finalized.validated, true);
    assert.equal(checks, 1);
    assert.equal(git(repo.workingDir, ["status", "--porcelain"]), "");
    assert.deepEqual(
      git(repo.workingDir, ["diff", "--name-only", `${repo.base}..HEAD`]).split(
        "\n",
      ),
      ["generated.txt"],
    );
  } finally {
    repo.cleanup();
  }
});

test("explicit preparation discard permits no-change finalization without a commit", async () => {
  const repo = preparedTaskFixture("runtime-preparation-discard-c3d4e5f6");
  try {
    let checks = 0;
    const events: string[] = [];
    const runtime = runtimeFor(
      repo,
      async () => {
        checks += 1;
        return { exitCode: 0, stdout: "passed\n", stderr: "" };
      },
      new AbortController().signal,
      undefined,
      recordingTarget(repo.target, events),
    );
    runtime.beginAttempt(1);

    const finalized = await runtime.host.finalize({
      commitPaths: [],
      discardPaths: ["generated.txt"],
      summary:
        "Discard the generated preparation output and verify no task changes remain.",
    });

    assert.equal(finalized.validated, true);
    assert.equal(finalized.status, "satisfied_without_changes");
    assert.equal(finalized.commit, undefined);
    assert.equal(checks, 1);
    assert.deepEqual(events, ["prepare"]);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), repo.base);
    assert.equal(
      fs.readFileSync(path.join(repo.workingDir, "generated.txt"), "utf8"),
      "base\n",
    );
    assert.equal(git(repo.workingDir, ["status", "--porcelain"]), "");
  } finally {
    repo.cleanup();
  }
});

test("preparation disposition precedes commit, amend, and empty finalization", async () => {
  const repo = fixture("runtime-preparation-ordering-d4e5f6a7");
  try {
    const events: string[] = [];
    let checks = 0;
    const target = recordingTarget(repo.target, events);
    const runtime = runtimeFor(
      repo,
      async () => ({
        exitCode: ++checks === 3 ? 0 : 1,
        stdout: "",
        stderr: "",
      }),
      new AbortController().signal,
      undefined,
      target,
    );
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "first\n");
    const first = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Create the provisional task commit.",
    });
    assert.equal(first.validated, false);
    assert.deepEqual(events, ["prepare", "commit"]);

    runtime.settleAttempt({ status: "settled", error: first.error });
    runtime.beginAttempt(2, first.error);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "second\n");
    const second = await runtime.host.finalize({
      commitPaths: ["selected.txt"],
      summary: "Amend the provisional task commit.",
    });
    assert.equal(second.validated, false);
    assert.deepEqual(events, ["prepare", "commit", "prepare", "amend"]);

    runtime.settleAttempt({ status: "settled", error: second.error });
    runtime.beginAttempt(3, second.error);
    const finalized = await runtime.host.finalize({
      commitPaths: [],
      summary: "Validate the unchanged amended task commit.",
    });
    assert.equal(finalized.validated, true);
    assert.deepEqual(events, [
      "prepare",
      "commit",
      "prepare",
      "amend",
      "prepare",
    ]);
  } finally {
    repo.cleanup();
  }
});

test("preparation discard cannot silently discard unrelated task changes", async () => {
  const repo = preparedTaskFixture("runtime-preparation-unrelated-e5f6a7b8");
  try {
    let checks = 0;
    const runtime = runtimeFor(repo, async () => {
      checks += 1;
      return { exitCode: 0, stdout: "passed\n", stderr: "" };
    });
    runtime.beginAttempt(1);
    fs.writeFileSync(
      path.join(repo.workingDir, "selected.txt"),
      "task change\n",
    );

    await assert.rejects(
      runtime.host.finalize({
        commitPaths: [],
        discardPaths: ["generated.txt"],
        summary: "Discard preparation output without discarding task work.",
      }),
    );
    assert.equal(checks, 0);
    assert.equal(runtime.snapshot().status, "running");
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), repo.base);
    assert.equal(
      fs.readFileSync(path.join(repo.workingDir, "selected.txt"), "utf8"),
      "task change\n",
    );
  } finally {
    repo.cleanup();
  }
});

test("discard selections require target preparation disposition support", async () => {
  const repo = preparedTaskFixture("runtime-preparation-unsupported-f6a7b8c9");
  try {
    let checks = 0;
    const target: FeatureTaskGitTarget = {
      ...repo.target,
      prepareFinalization: undefined,
    };
    const runtime = runtimeFor(
      repo,
      async () => {
        checks += 1;
        return { exitCode: 0, stdout: "passed\n", stderr: "" };
      },
      new AbortController().signal,
      undefined,
      target,
    );
    runtime.beginAttempt(1);
    const generated = path.join(repo.workingDir, "generated.txt");
    const beforeContent = fs.readFileSync(generated, "utf8");

    await assert.rejects(
      runtime.host.finalize({
        commitPaths: [],
        discardPaths: ["generated.txt"],
        summary: "The target must support explicit preparation discard.",
      }),
    );
    assert.equal(checks, 0);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), repo.base);
    assert.equal(fs.readFileSync(generated, "utf8"), beforeContent);
  } finally {
    repo.cleanup();
  }
});

test("a failed check preserves the provisional preparation commit for retry", async () => {
  const repo = preparedTaskFixture("runtime-preparation-retry-a7b8c9d0");
  try {
    let checks = 0;
    const runtime = runtimeFor(repo, async () => ({
      exitCode: ++checks === 1 ? 1 : 0,
      stdout: checks === 1 ? "failed\n" : "passed\n",
      stderr: "",
    }));
    runtime.beginAttempt(1);
    fs.writeFileSync(path.join(repo.workingDir, "selected.txt"), "task\n");

    const first = await runtime.host.finalize({
      commitPaths: ["generated.txt", "selected.txt"],
      summary:
        "Commit task work and verified preparation output before retrying checks.",
    });
    assert.equal(first.validated, false);
    assert.equal(first.status, "provisional");
    assert.ok(first.commit);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), first.commit);
    assert.equal(git(repo.workingDir, ["status", "--porcelain"]), "");

    runtime.settleAttempt({ status: "settled", error: first.error });
    const retry = runtime.beginAttempt(2, first.error);
    assert.equal(retry.graphContext.provisionalCommit, first.commit);
    assert.deepEqual(retry.graphContext.preparationChanges, []);
    assert.equal(retry.graphContext.previousChecks[0]?.status, "failed");

    const finalized = await runtime.host.finalize({
      commitPaths: [],
      summary:
        "Recheck the unchanged task commit after the failed verification.",
    });
    assert.equal(finalized.validated, true);
    assert.equal(finalized.commit, first.commit);
    assert.equal(checks, 2);
    assert.equal(git(repo.workingDir, ["rev-parse", "HEAD"]), first.commit);
    assert.deepEqual(
      git(repo.workingDir, ["diff", "--name-only", `${repo.base}..HEAD`])
        .split("\n")
        .sort(),
      ["generated.txt", "selected.txt"],
    );
  } finally {
    repo.cleanup();
  }
});
